language: android
dist: trusty
sudo: false

android:
  components:
    - build-tools-28.0.3
    - android-28

before_install:
  - yes | sdkmanager "platforms;android-29"


licenses:
    - 'android-sdk-license-.+'

script:
  - ./gradlew build